name: Deploy Fullstack to VPS

on:
  push:
    branches:
      - master  # Hoặc branch bạn muốn deploy

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install SSH Client & sshpass
        run: sudo apt-get install -y sshpass

      - name: Deploy Backend & Frontend
        run: |
          sshpass -p "${{ secrets.PASSWORD }}" ssh -o StrictHostKeyChecking=no ${{ secrets.USER_NAME }}@${{ secrets.HOST }} << 'EOF'
            # Chạy trên VPS
            cd /home/Hachitech_project
            # Deploy Frontend
            cd nextjs-app/
            git pull origin master
            npm install
            npm run build
            cp -r .next/static/* /var/www/html/
            # Deploy Backend
            cd ../backend_hachitech
            git pull origin master
            npm install
            pm2 restart all  # Hoặc restart server nếu cần
            echo "✅ Deployment completed!"
          EOF
