name: Deploy Fullstack to VPS

on:
  push:
    branches:
      - master  # Hoặc nhánh bạn đang sử dụng

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.VPS_SSH_KEY }}" | tr -d '\r' > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.HOST }} >> ~/.ssh/known_hosts

      - name: Deploy Backend & Frontend
        run: |
          ssh -i ~/.ssh/id_rsa root@${{ secrets.HOST }} << 'EOF'
            # Chạy trong VPS
            cd /home/Hachitech_project

            # Deploy backend
            cd backend_hachitech
            git pull origin master
            npm install
            pm2 restart all  # Hoặc restart server nếu cần

            # Deploy frontend
            cd ../nextjs-app
            git pull origin master
            npm install
            npm run build
            cp -r .next/static/* /var/www/html/

            echo "✅ Deployment completed!"
          EOF
